<a href="https://colab.research.google.com/github/PushpaYa/doclm/blob/main/NeighborswithLayoutLMv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!rm -r transformers
!git clone -b modeling_layoutlmv2_v2 https://github.com/NielsRogge/transformers.git
!cd tranformers
!pip install -q ./transformers

rm: cannot remove 'transformers': No such file or directory
Cloning into 'transformers'...
remote: Enumerating objects: 105031, done.
remote: Total 105031 (delta 0), reused 0 (delta 0), pack-reused 105031
Receiving objects: 100% (105031/105031), 82.52 MiB | 13.51 MiB/s, done.
Resolving deltas: 100% (76178/76178), done.
/bin/bash: line 0: cd: tranformers: No such file or directory
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 67 kB 2.9 MB/s 
     |████████████████████████████████|

In [2]:
!pip install -q datasets==1.11.0 seqeval

     |████████████████████████████████| 264 kB 4.2 MB/s 
     |████████████████████████████████| 43 kB 2.7 MB/s 
     |████████████████████████████████| 56 kB 6.7 MB/s 
     |████████████████████████████████| 133 kB 84.0 MB/s 
     |████████████████████████████████| 243 kB 81.2 MB/s 


In [3]:
!pip install -q pyyaml==5.1
# workaround: install old version of pytorch since detectron2 hasn't released packages for pytorch 1.9 (issue: https://github.com/facebookresearch/detectron2/issues/3158)
!pip install -q torch==1.8.0+cu101 torchvision==0.9.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

# install detectron2 that matches pytorch 1.8
# See https://detectron2.readthedocs.io/tutorials/install.html for instructions
#!pip install -q detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.8/index.html
!python -m pip install -q 'git+https://github.com/facebookresearch/detectron2.git'

     |████████████████████████████████| 274 kB 4.2 MB/s 
     |████████████████████████████████| 763.5 MB 15 kB/s 
     |████████████████████████████████| 17.3 MB 42.2 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.11.0 requires torch==1.10.0, but you have torch 1.8.0+cu101 which is incompatible.
torchaudio 0.10.0+cu111 requires torch==1.10.0, but you have torch 1.8.0+cu101 which is incompatible.
     |████████████████████████████████| 55 kB 2.3 MB/s 
     |████████████████████████████████| 74 kB 3.6 MB/s 
     |████████████████████████████████| 145 kB 36.0 MB/s 
     |████████████████████████████████| 130 kB 85.1 MB/s 
     |████████████████████████████████| 38.1 MB 1.5 MB/s 
     |████████████████████████████████| 843 kB 28.4 MB/s 
     |████████████████████████████████| 748 kB 75.4 MB/s 
     |████████████████████████████████| 112 kB 97.7 

In [4]:
!pip install pyyaml==5.1

import torch
TORCH_VERSION = ".".join(torch.__version__.split(".")[:2])
CUDA_VERSION = torch.__version__.split("+")[-1]
print("torch: ", TORCH_VERSION, "; cuda: ", CUDA_VERSION)
# Install detectron2 that matches the above pytorch version
# See https://detectron2.readthedocs.io/tutorials/install.html for instructions
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/$CUDA_VERSION/torch$TORCH_VERSION/index.html
# If there is not yet a detectron2 release that matches the given torch + CUDA version, you need to install a different pytorch.

# exit(0)  # After installation, you may need to "restart runtime" in Colab. This line can also restart runtime

torch:  1.8 ; cuda:  cu101
Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.8/index.html


In [5]:
!pip install -q pytesseract

In [6]:
! pip install transformers datasets

In [7]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [22]:
# !unzip gdrive/MyDrive/datasetLMv2LayoutLMv4.zip
!unzip /content/dataset.zip

Archive:  /content/dataset.zip
  inflating: dataset/.DS_Store       
  inflating: dataset/bertembeddingfornull.json  
   creating: dataset/testing_data/
  inflating: dataset/testing_data/.DS_Store  
   creating: dataset/testing_data/annotations/
  inflating: dataset/testing_data/annotations/82092117.json  
  inflating: dataset/testing_data/annotations/82200067_0069.json  
  inflating: dataset/testing_data/annotations/82250337_0338.json  
  inflating: dataset/testing_data/annotations/82251504.json  
  inflating: dataset/testing_data/annotations/82252956_2958.json  
  inflating: dataset/testing_data/annotations/82253058_3059.json  
  inflating: dataset/testing_data/annotations/82253245_3247.json  
  inflating: dataset/testing_data/annotations/82253362_3364.json  
  inflating: dataset/testing_data/annotations/82254765.json  
  inflating: dataset/testing_data/annotations/82491256.json  
  inflating: dataset/testing_data/annotations/82504862.json  
  inflating: dataset/testing_data/annotati

# New Section

In [9]:
!pip install timm

     |████████████████████████████████| 431 kB 4.3 MB/s 


In [23]:
import pandas as pd
import os
dirpath="/content/dataset"
dataset_path_train = "/content/dataset/training_data/images"
dataset_path_test = "/content/dataset/testing_data/images"
labels = ['O', 'B-HEADER', 'I-HEADER', 'B-QUESTION', 'I-QUESTION', 'B-ANSWER', 'I-ANSWER']
idx2label = {v: k for v, k in enumerate(labels)}
label2idx = {k: v for v, k in enumerate(labels)}
label2idx

{'B-ANSWER': 5,
 'B-HEADER': 1,
 'B-QUESTION': 3,
 'I-ANSWER': 6,
 'I-HEADER': 2,
 'I-QUESTION': 4,
 'O': 0}

In [24]:
def create_img_path(dataset_path):
    images_train = []
    dataset_fldr= dataset_path.split("/")[-2]
    for label_folder, _, file_names in os.walk(dataset_path):
      
      for _, _, image_names in os.walk(label_folder):
          #print(dataset_fldr)
          relative_image_names = []
          for image in image_names:
            relative_image_names.append( dirpath + "/"+dataset_fldr+'/images/'+ image)
          images_train.extend(relative_image_names)
          #print(relative_image_names)
    return images_train

image_path = create_img_path(dataset_path_train)
traindata_ = pd.DataFrame.from_dict({'image_path': image_path})




image_path = create_img_path(dataset_path_test)
testdata_ = pd.DataFrame.from_dict({'image_path': image_path})


In [ ]:
#testdata_

In [25]:
import os
import json
from datasets import Dataset
from PIL import Image, ImageDraw, ImageFont
dirpath="/content/dataset"
def generate_examples(example):
        path = example['image_path']
        image = Image.open(path)
        w,h = image.size
        filename = path.split('/')[-1]
        filename = filename.split('.')[0]
        datdir=path.split('/')[-3]
        #print(datdir)
        f = open(dirpath + '/' + datdir + '/changed/'+ filename + '.json')
        data = json.load(f)
        words = []
        boxes = []
        neighbors = []
        labels = []
        #print(data)
        for i in data:
          words.append(i['text'])
          unnormalized_box = i['box']
          normalized_box = unnormalized_box
          # if(i['text'] not in words_dictionary):
          #   global id
          #   words_dictionary[str(i['text'])] = id
          #   box_dictionary[id] = normalized_box
          #   id+=1
          boxes.append(normalized_box)
          neighbors.append(i['neighbors'])
          labels.append(label2idx[i['label']])
        # normalize the bounding boxes
        # add as extra columns 
        assert len(words) == len(boxes)
        example['words'] = words
        example['bbox'] = boxes

        example['neighbors'] = neighbors
        example['labels'] = labels
        return example

In [27]:
traindata = Dataset.from_pandas(traindata_)
train = traindata.map(generate_examples)
testdata = Dataset.from_pandas(testdata_)
test = testdata.map(generate_examples)

  0%|          | 0/149 [00:00<?, ?ex/s]

  0%|          | 0/50 [00:00<?, ?ex/s]

In [28]:
test.column_names,test.shape,test.features

(['image_path', 'words', 'bbox', 'neighbors', 'labels'],
 (50, 5),
 {'bbox': Sequence(feature=Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), length=-1, id=None),
  'image_path': Value(dtype='string', id=None),
  'labels': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None),
  'neighbors': Sequence(feature=Sequence(feature=Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), length=-1, id=None), length=-1, id=None),
  'words': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)})

In [29]:
test

Dataset({
    features: ['image_path', 'words', 'bbox', 'neighbors', 'labels'],
    num_rows: 50
})

In [30]:
from PIL import Image
import numpy as np
from transformers import LayoutLMv2Processor
from datasets import Features, Sequence, ClassLabel, Value, Array2D, Array3D
from torchvision.transforms import ToTensor
processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")



# we need to define custom features
features = Features({
    'image': Array3D(dtype="int64", shape=(3, 224, 224)),
    'labels': Sequence(feature=Value(dtype='int64')),
    'bbox': Array2D(dtype="int64", shape=(512, 4)),     
   
    'input_ids': Sequence(feature=Value(dtype='int64')),
    'attention_mask': Sequence(Value(dtype='int64')),
    'token_type_ids': Sequence(Value(dtype='int64')),
    'neighbors': Sequence(feature=Sequence(feature=Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), length=-1, id=None), length=-1, id=None)
    
})




def preprocess_data(examples):
  #print(examples['image_path'])
  path = examples['image_path']
  images = Image.open(path).convert("RGB")
  words = examples['words']
  bbox = examples['bbox']
  word_labels = examples['labels']
  
  encoded_inputs = processor(images, words, boxes=bbox, word_labels=word_labels,
                             padding="max_length", truncation=True)
  
   

  #print( len(encoded_inputs['image']))
  del examples['words']
  del examples['image_path']
  #print(len(encoded_inputs['input_ids']))
   # get required padding length
  pad_len = 512 - len(examples['neighbors'])
  token_neighbors = [[[0]*6]*12]*pad_len
  #print(token_neighbors)
  examples['neighbors'] = examples['neighbors'] + token_neighbors
  
  dict1 = {'neighbors':list(examples['neighbors'])}
  #dict1 = {'neighbors':examples['neighbors']}
  encoded_inputs.update(dict1)
  encoded_inputs["image"] = np.array(encoded_inputs["image"])
  



  
  
  return encoded_inputs


#test_dataset = test.map(preprocess_data, batched=True, remove_columns=test.column_names,
                                      #eatures=features)
#train_dataset =train.map(preprocess_data, batched=True, remove_columns=train.column_names,
                                      #features=features)




#encoded_dataset = train.map(lambda examples: preprocess_data(examples), batched=True)

In [31]:
import torch
train_dataset = []
for example in train:
    #print(example)
    processed_example = preprocess_data(example)
    example.update(processed_example)
    train_dataset.append(example)



test_dataset = []
for example in test:
    #print(example)
    processed_example = preprocess_data(example)
    example.update(processed_example)
    test_dataset.append(example)

In [32]:
encoding = train_dataset[0]
print(processor.tokenizer.decode(encoding['input_ids']))

[CLS] b164 ph reference : oral solubility acute cadcovascular reference : 00865872 compound to sensitive signature : [ ] other [ moisture ] [ ] heat [ ] air safety procedure ( suggested comment : date 8 / 22 / 83 compound physical parameters lrc file number lot number physical state brownish - gray powder the ph of a 50 % concentration of b164 in water was calculated to be 4. 82 at 25°c according to the extrapolation procedures by dr. p. d. schickedantz, lorillard research center accession number 1662. ( see sop fox biological solutions ) bc20 - 48 b164 forms a suspension in corn oil at 0. 5g / 1. 5 ml triple dosing is required ( see sop for determination of solubility of materials for acute cardiovascular and respiratory effects study beagle dogs ) bc20 - 48 b164 is insoluble according to this procedure storage recommendations refrigerate in amber glass bottle at no more than 8°c lorillard research center form 1921 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD

In [ ]:
encoding.keys()

dict_keys(['bbox', 'neighbors', 'labels', 'input_ids', 'token_type_ids', 'attention_mask', 'image'])

In [ ]:
encoding['image'][0].shape

(3, 224, 224)

In [ ]:
for k,v in encoding.items():
  print(k, len(v))
#encoding['neighbors']

bbox 512
neighbors 512
labels 512
input_ids 512
token_type_ids 512
attention_mask 512
image 1


In [33]:
from torch.utils.data.dataloader import default_collate
from torchvision.transforms import ToTensor
def collate_fn(batch):
   elem = batch[0]
   #print(type(elem))
   bbox = [item['bbox'] for item in batch]  # just form a list of tensor
   neighbors = [item['neighbors'] for item in batch]
   labels = [item['labels'] for item in batch]
   input_ids = [item['input_ids'] for item in batch]
   token_type_ids = [item['token_type_ids'] for item in batch]
   attention_mask = [item['attention_mask'] for item in batch]
   image =  [item['image'] for item in batch][0]
   elem= {'bbox' : torch.tensor(bbox), 'neighbors':torch.tensor(neighbors),'labels':torch.Tensor(labels),'input_ids':torch.Tensor(input_ids),'token_type_ids':torch.Tensor(token_type_ids),'attention_mask':torch.Tensor(attention_mask),'image':torch.Tensor(image)}
   #return dict(bbox = bbox, neighbors=neighbors,labels=labels,input_ids=input_ids,token_type_ids=token_type_ids,attention_mask=attention_mask,image=image)
   #transposed = zip(*batch)
   #return [default_collate(samples) for samples in transposed]
   return elem

In [34]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_dataset, batch_size=1, shuffle=True, num_workers=0,  collate_fn=collate_fn)
test_dataloader = DataLoader(test_dataset, batch_size=1,shuffle=True, num_workers=0,  collate_fn=collate_fn)

In [35]:
batch = next(iter(train_dataloader))

for k ,v in batch.items():
    print(k,type(v))


bbox <class 'torch.Tensor'>
neighbors <class 'torch.Tensor'>
labels <class 'torch.Tensor'>
input_ids <class 'torch.Tensor'>
token_type_ids <class 'torch.Tensor'>
attention_mask <class 'torch.Tensor'>
image <class 'torch.Tensor'>


In [36]:
for k,v in batch.items():
  print(k, batch[k].shape)

bbox torch.Size([1, 512, 4])
neighbors torch.Size([1, 512, 12, 6])
labels torch.Size([1, 512])
input_ids torch.Size([1, 512])
token_type_ids torch.Size([1, 512])
attention_mask torch.Size([1, 512])
image torch.Size([1, 3, 224, 224])


In [37]:
import torch
device = torch.device('cuda')

In [38]:
pip install pytorch-nlp

     |████████████████████████████████| 90 kB 3.8 MB/s 


In [39]:
import torch.nn as nn
from transformers import LayoutLMv2Model
from transformers.models.layoutlm import LayoutLMConfig
from transformers.modeling_outputs import TokenClassifierOutput
import torchvision
from torchvision.ops import RoIAlign
import torch
import numpy as np
from torchnlp.nn import Attention
import time 

In [40]:


class LayoutLMv2ForTokenClassification(nn.Module):
    def __init__(self): 
        super().__init__()
        self.start_time = time.time()
        # LayoutLM base model + token classifier
        self.num_labels = len(label2idx)
        self.layoutlm = LayoutLMv2Model.from_pretrained("microsoft/layoutlmv2-base-uncased", num_labels=self.num_labels)
        
        self.mlp = nn.Linear(13*768,12*768)
        self.sigmoid = nn.Sigmoid()
        self.attn = Attention(768)

        self.dropout = nn.Dropout(self.layoutlm.config.hidden_dropout_prob)
        self.classifier = nn.Linear(2*768, self.num_labels)

    def forward(self,image,input_ids,bbox,attention_mask,token_type_ids,neighbors,inputs_embeds=None,position_ids=None,head_mask=None,
        labels=None,output_attentions=None,output_hidden_states=None,return_dict=None,):
        r"""
        labels (:obj:`torch.LongTensor` of shape :obj:`(batch_size, sequence_length)`, `optional`):
            Labels for computing the token classification loss. Indices should be in ``[0, ..., config.num_labels -
            1]``.

        """
        return_dict = return_dict if return_dict is not None else self.layoutlm.config.use_return_dict
        # print('layoutlm Start',time.time()-self.start_time)
        # first, forward pass on LayoutLM
        outputs = self.layoutlm(
            image=image,
            input_ids=input_ids,
            bbox=bbox,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            head_mask=head_mask,
            inputs_embeds = inputs_embeds,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )
        # print('layoutlm End',time.time()-self.start_time)
        # print(self.layoutlm.config.hidden_size)
        if input_ids is not None:
            input_shape = input_ids.size()
        else:
            input_shape = inputs_embeds.size()[:-1]

        seq_length = input_shape[1]
        sequence_output = outputs[0][:, :seq_length]
        dictionary = {}
        batchsize = sequence_output.shape[0]
        final_neighbors = []
        # print('Making Neighbours',time.time()-self.start_time)
        for batch in range(batchsize):
          for i in range(512):
            dictionary[int(input_ids[batch][i])] = sequence_output[batch][i]
          l = []
          for i in range(512):
            # for n in neighbors[batch]:
            temp = []
            temp = torch.Tensor(temp)  
            for j in range(12):
              word_tokens = neighbors[batch][i][j]
              embed = torch.zeros(768)
              for w in word_tokens:
                if(w in dictionary):
                  embed = torch.add(embed,dictionary[w])
                else:
                  embed = torch.add(embed,torch.zeros(768))
              temp = torch.cat((temp,embed),0)
              # print('temp',temp.shape)
              # temp = torch.stack(temp)
            l.append(temp)
          l = torch.stack(l)
          final_neighbors.append(l)
        final_neighbors = torch.stack(final_neighbors)
        # print('final_neighbors',final_neighbors.shape)
        neighbors = final_neighbors.to(device)
        # print('Neighbours Made',time.time()-self.start_time)
        # print(neighbors.shape)
        # print('Gating and Attention Start',time.time()-self.start_time)
        final_output = []
        batchsize = sequence_output.shape[0]
        for i in range(batchsize): 
          temp = []
          for row,n in zip(sequence_output[i],neighbors[i]):
            # print(row.shape,n.shape)
            rij = torch.cat((row,n),0)
            # print(row.shape)
            wr = self.mlp(rij)
            # print(wr.shape)
            g = self.sigmoid(wr)
            # print(g.shape)
            c_dash = torch.mul(g,n)
            # print(c_dash.shape)
            c_dash = torch.reshape(c_dash,(12,768))
            c_dash = c_dash.unsqueeze(0)
            row = row.unsqueeze(0)
            row = row.unsqueeze(0)
            # print(row.shape)
            # print(c_dash.shape)
            output,weights = self.attn(row,c_dash)
            temp.append(output[0][0])
          temp = torch.stack(temp)
          # temp = .unsqueeze(0)
          # print(final_output.shape)
          final_output.append(temp)
        final_output = torch.stack(final_output)
        final_output = torch.cat((sequence_output,final_output),2)
        # print('Gating And Attention End',time.time()-self.start_time)
        # print(final_output.shape)
        # print('Classification Start',time.time()-self.start_time)
        final_output = self.dropout(final_output)
        logits = self.classifier(final_output)
        # attention_mask = torch.cat((attention_mask,attention_mask),1)
        # labels = torch.cat((labels,labels),1)
        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()

            if attention_mask is not None:
                active_loss = attention_mask.view(-1) == 1
                active_logits = logits.view(-1, self.num_labels)[active_loss]
                active_labels = labels.view(-1)[active_loss]
                loss = loss_fct(active_logits, active_labels)
            else:
                loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))

        if not return_dict:
            output = (logits,) + outputs[2:]
            return ((loss,) + output) if loss is not None else output
        # print('Classification End',time.time()-self.start_time)
        return TokenClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )

In [41]:
model = LayoutLMv2ForTokenClassification()
device = torch.device('cuda:0')
model = model.to(device)

Downloading:   0%|          | 0.00/802M [00:00<?, ?B/s]

Some weights of the model checkpoint at microsoft/layoutlmv2-base-uncased were not used when initializing LayoutLMv2Model: ['layoutlmv2.visual.backbone.bottom_up.res3.3.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.10.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res3.0.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.0.shortcut.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.1.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.2.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.0.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.7.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.17.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.7.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.3.conv1.norm.num_batches_tracked', 'layoutlmv2.v

In [42]:
batch.keys()

dict_keys(['bbox', 'neighbors', 'labels', 'input_ids', 'token_type_ids', 'attention_mask', 'image'])

In [43]:
input_ids=batch['input_ids'].long().cuda()
bbox=batch['bbox'].long().cuda()
attention_mask=batch['attention_mask'].long().cuda()
token_type_ids=batch['token_type_ids'].long().cuda()
labels=batch['labels'].long().cuda()
resized_images = batch['image'].long().cuda() # shape (N, C, H, W), with H = W = 224
neighbors = batch['neighbors'].long().cuda()

outputs = model(input_ids=input_ids, bbox=bbox, attention_mask=attention_mask, token_type_ids=token_type_ids, 
                labels=labels, image=resized_images, neighbors=neighbors)

In [44]:
outputs.loss


tensor(1.9420, device='cuda:0', grad_fn=<NllLossBackward>)

In [47]:
from transformers import AdamW
import torch
from tqdm.notebook import tqdm

In [ ]:
from sklearn.model_selection import KFold
from torch.utils.data import SubsetRandomSampler,DataLoader,TensorDataset
import pprint
import numpy
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score,
)
import cv2
# k_folds = 10
results = []
# kfold = KFold(n_splits=k_folds, shuffle=False)
num_train_epochs = 15
t_total = len(train_dataloader) * num_train_epochs # total number of training steps 

model = LayoutLMv2ForTokenClassification()
#model = nn.DataParallel(model)
device = torch.device('cuda:0')
model.to(device)
optimizer = AdamW(model.parameters(), lr=2.373260750776288e-05)
# wandb.init(name='First Run', 
#           project='FinalResultsWithFullDatasetwith45epochs',
#           notes='FinalResultsWithFullDataset', 
#           tags=['FinalResultsWithFullDataset'])
global_step = 0
# wandb.watch(model)
model.train() 
for epoch in range(num_train_epochs):  
  print("Epoch:", epoch)
  for batch in tqdm(train_dataloader):
        # input_ids = torch.Tensor(list(batch['input_ids'].values)).to(device)
        input_ids = batch['input_ids'].long().cuda()
        image = batch['image'].long().cuda()
        bbox = batch["bbox"].long().cuda()
        attention_mask = batch["attention_mask"].long().cuda()
        token_type_ids = batch["token_type_ids"].long().cuda()
        labels = batch["labels"].long().cuda()
        neighbors = batch['neighbors'].long().cuda()
        # print(batch)
        # zero the parameter gradients
        optimizer.zero_grad()
        outputs = model(labels=labels,
                      input_ids= input_ids,
                      bbox=bbox, 
                      attention_mask=attention_mask,
                      token_type_ids=token_type_ids,
                      image=image,
                      neighbors=neighbors)
        # forward + backward + optimize
        # outputs = model(input_ids=input_ids,image=image,bbox=bbox,attention_mask=attention_mask,token) 
        loss = outputs.loss
        
        # print loss every 100 steps
        if global_step % 100 == 0:
          print(f"Loss after {global_step} steps: {loss.item()}")
        # wandb.log({
        # "Epoch": epoch,
        # "Train Loss": loss.item()})
        loss.backward()
        optimizer.step()
        global_step += 1

Some weights of the model checkpoint at microsoft/layoutlmv2-base-uncased were not used when initializing LayoutLMv2Model: ['layoutlmv2.visual.backbone.bottom_up.res4.20.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.5.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.8.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.2.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.22.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res2.1.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.1.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.5.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res3.3.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.12.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.13.conv1.norm.num_batches_tracked', 'layoutlmv2.vi

Epoch: 0


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 0 steps: 1.927445411682129
Loss after 100 steps: 1.3497968912124634
Epoch: 1


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 200 steps: 0.5693944096565247
Epoch: 2


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 300 steps: 0.36955901980400085
Loss after 400 steps: 0.38724085688591003
Epoch: 3


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 500 steps: 0.19227568805217743
Epoch: 4


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 600 steps: 0.22544528543949127
Loss after 700 steps: 0.2935468256473541
Epoch: 5


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 800 steps: 0.08799637854099274
Epoch: 6


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 900 steps: 0.19784465432167053
Loss after 1000 steps: 0.1403467208147049
Epoch: 7


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 1100 steps: 0.24261781573295593
Epoch: 8


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 1200 steps: 0.15977440774440765
Loss after 1300 steps: 0.029750747606158257
Epoch: 9


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 1400 steps: 0.056862570345401764
Epoch: 10


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 1500 steps: 0.11870735138654709
Loss after 1600 steps: 0.059717439115047455
Epoch: 11


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 1700 steps: 0.2403654009103775
Epoch: 12


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 1800 steps: 0.015798885375261307
Loss after 1900 steps: 0.06496880203485489
Epoch: 13


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 2000 steps: 0.05331740900874138
Epoch: 14


  0%|          | 0/149 [00:00<?, ?it/s]

Loss after 2100 steps: 0.2755671441555023
Loss after 2200 steps: 0.13266225159168243


In [53]:
save_path = f'/content/gdrive/MyDrive/final_model_15epochs.pth'
#torch.save(model.state_dict(), save_path)

In [54]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import confusion_matrix,multilabel_confusion_matrix, classification_report
import numpy as np
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score,
)
eval_loss = 0.0
nb_eval_steps = 0
preds = None
out_label_ids = None
# testmodel = model
# # put model in evaluation mode
# testmodel.eval()
testmodel = LayoutLMv2ForTokenClassification()
testmodel.load_state_dict(torch.load(save_path))
testmodel.to(device)
for batch in tqdm(test_dataloader, desc="Evaluating"):
    with torch.no_grad():
        input_ids=batch['input_ids'].long().cuda()
        bbox=batch['bbox'].long().cuda()
        attention_mask=batch['attention_mask'].long().cuda()
        token_type_ids=batch['token_type_ids'].long().cuda()
        labels=batch['labels'].long().cuda()
        image = batch['image'].long().cuda()
        neighbors = batch['neighbors'].long().cuda()
        # resized_images = batch['resized_image'].to(device) 
        # resized_and_aligned_bounding_boxes = batch['resized_and_aligned_bounding_boxes'].to(device) 

        # forward pass
        outputs = testmodel(input_ids=input_ids, bbox=bbox, attention_mask=attention_mask, token_type_ids=token_type_ids, 
                        labels=labels,image=image,neighbors=neighbors)

        # get the loss and logits
        tmp_eval_loss = outputs.loss
        logits = outputs.logits

        eval_loss += tmp_eval_loss.item()
        nb_eval_steps += 1

        # compute the predictions
        if preds is None:
            preds = logits.detach().cpu().numpy()
            out_label_ids = labels.detach().cpu().numpy()
        else:
            preds = np.append(preds, logits.detach().cpu().numpy(), axis=0)
            out_label_ids = np.append(
                out_label_ids, labels.detach().cpu().numpy(), axis=0
            )

# compute average evaluation loss
eval_loss = eval_loss / nb_eval_steps
preds = np.argmax(preds, axis=2)

out_label_list = [[] for _ in range(out_label_ids.shape[0])]
preds_list = [[] for _ in range(out_label_ids.shape[0])]

for i in range(out_label_ids.shape[0]):
    for j in range(out_label_ids.shape[1]):
        if out_label_ids[i, j] != -100:
            out_label_list[i].append(idx2label[out_label_ids[i][j]])
            preds_list[i].append(idx2label[preds[i][j]])

testresults = {
    "loss": eval_loss,
    "precision": precision_score(out_label_list, preds_list),
    "recall": recall_score(out_label_list, preds_list),
    "f1": f1_score(out_label_list, preds_list),
    "classification_report": classification_report(out_label_list, preds_list)
    # "confusion_matrix": multilabel_confusion_matrix(MultiLabelBinarizer().fit_transform(out_label_list), MultiLabelBinarizer().fit_transform(preds_list))
    # "confusion_matrix": confusion_matrix(MultiLabelBinarizer().fit_transform(out_label_list), MultiLabelBinarizer().fit_transform(preds_list))
}
print(out_label_list)
print(preds_list)
print(testresults)

Some weights of the model checkpoint at microsoft/layoutlmv2-base-uncased were not used when initializing LayoutLMv2Model: ['layoutlmv2.visual.backbone.bottom_up.res3.3.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.10.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res3.0.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.0.shortcut.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.1.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.2.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res5.0.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.7.conv2.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.17.conv1.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.7.conv3.norm.num_batches_tracked', 'layoutlmv2.visual.backbone.bottom_up.res4.3.conv1.norm.num_batches_tracked', 'layoutlmv2.v

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

[['B-QUESTION', 'B-QUESTION', 'B-QUESTION', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-HEADER', 'I-HEADER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-HEADER', 'I-HEADER', 'B-ANSWER', 'I-ANSWER', 'I-ANSWER', 'B-ANSWER', 'I-ANSWER', 'I-ANSWER', 'I-ANSWER', 'I-ANSWER', 'I-ANSWER', 'I-ANSWER', 'B-ANSWER', 'I-ANSWER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-QUESTION', 'I-QUESTION', 'I-QUESTION', 'B-ANSWER', 'I-ANSWER', 'I-ANSWER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'], ['B-QUESTION', 'B-QUESTION', 'O', 'B-QUESTION', 'B-QUESTION', 'O', 'B-HEADER', 'I-HEADER', 'I-HEADER', 'B

In [55]:
labels_list = []
for i in out_label_list:
  labels_list.extend(i)
preds = []
for i in preds_list:
  preds.extend(i)
print(confusion_matrix(labels_list,preds,labels=['O', 'B-HEADER', 'I-HEADER', 'B-QUESTION', 'I-QUESTION', 'B-ANSWER', 'I-ANSWER']))

[[1766   15  157   33  177   29  179]
 [   4   70    1   38    2    4    0]
 [  35    1  167    4   31    5   12]
 [  29    8    1  959   34   26    8]
 [ 111    0    5   19 1285    2   55]
 [  34    1    0   29    6  722   17]
 [ 341    0    1    4  133   50 1956]]


In [56]:
print(testresults["classification_report"])

              precision    recall  f1-score   support

      ANSWER       0.77      0.83      0.80       809
      HEADER       0.61      0.53      0.57       119
    QUESTION       0.81      0.86      0.83      1065

   micro avg       0.79      0.83      0.81      1993
   macro avg       0.73      0.74      0.73      1993
weighted avg       0.78      0.83      0.80      1993

